<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Promise的实现</title>
  </head>
  <body>
    <script>
      /**
       *
       */
      function Promise(executor) {
        var self = this;
        /*
        status:
        1. pending
        2. resolved
        3. rejected
        */
        self.status = "pending"; // Promise当前的状态
        self.data = undefined; // Promise的值
        self.onResolvedCallback = []; // Promise resolve时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
        self.onRejectedCallback = []; // Promise reject时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
        function resolve(value) {
          if (value instanceof Promise) {
            return value.then(resolve, reject);
          }
          setTimeout(function() {
            if (self.status === "pending") {
              self.status = "resolved";
              // 修改状态
              self.data = value;
              // 执行回调监听函数
              for (var i = 0; i < self.onResolvedCallback.length; i++) {
                self.onResolvedCallback[i](value);
              }
            }
          });
        }

        function reject(reason) {
          setTimeout(function() {
            if (self.status === "pending") {
              self.status = "rejected";
              // 修改状态
              self.data = reason;
              // 执行回调监听函数
              for (var i = 0; i < self.onRejectedCallback.length; i++) {
                self.onRejectedCallback[i](reason);
              }
            }
          });
        }
        try {
          // 考虑到执行executor的过程中有可能出错，所以我们用try/catch块给包起来，并且在出错后以catch到的值reject掉这个Promise
          executor(resolve, reject); // 执行executor
        } catch (e) {
          reject(e);
        }
      }

      // then方法接收两个参数，onResolved，onRejected，分别为Promise成功或失败后的回调
      Promise.prototype.then = function(onResolved, onRejected) {
        var self = this;
        var promise2;

        // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理
        onResolved =
          typeof onResolved === "function"
            ? onResolved
            : function(v) {
                return v;
              };
        onRejected =
          typeof onRejected === "function"
            ? onRejected
            : function(r) {
                return r;
              };

        // 如果promise1(此处即为this/self)的状态已经确定并且是resolved，我们调用onResolved
        if (self.status === "resolved") {
          // 因为考虑到有可能throw，所以我们将其包在try/catch块里
          return (promise2 = new Promise(function(resolve, reject) {
            setTimeout(function() {
              try {
                var x = onResolved(self.data);
                // 如果onResolved的返回值是一个Promise对象，直接取它的结果做为promise2的结果
                if (x instanceof Promise) {
                  x.then(resolve, reject);
                }
                resolve(x);
              } catch (error) {
                reject(error);
              }
            });
          }));
        }

        if (self.status === "rejected") {
          return (promise2 = new Promise(function(resolve, reject) {
            setTimeout(function() {
              try {
                var x = onRejected(self.data);
                if (x instanceof Promise) {
                  x.then(resolve, reject);
                }
              } catch (e) {
                reject(e);
              }
            });
          }));
        }

        if (self.status === "pending") {
          // 如果当前的Promise还处于pending状态，我们并不能确定调用onResolved还是onRejected，
          // 只能等到Promise的状态确定后，才能确实如何处理。
          // 所以我们需要把我们的**两种情况**的处理逻辑做为callback放入promise1(此处即this/self)的回调数组里
          return (promise2 = new Promise(function(resolve, reject) {
            self.onResolvedCallback.push(function(value) {
              try {
                var x = onResolved(self.data);
                if (x instanceof Promise) {
                  x.then(resolve, reject);
                }
                resolve(x);
              } catch (e) {
                reject(e);
              }
            });

            self.onRejectedCallback.push(function(reason) {
              try {
                var x = onRejected(self.data);
                if (x instanceof Promise) {
                  x.then(resolve, reject);
                }
              } catch (e) {
                reject(e);
              }
            });
          }));
        }
      };
      // 为了下文方便，我们顺便实现一个catch方法
      Promise.prototype.catch = function(onRejected) {
        return this.then(null, onRejected);
      };
      // 使用
      // Promise构造函数接收一个executor函数，executor函数执行完同步或异步操作后，调用它的两个参数resolve和reject
      let promise = new Promise(resolve => {
        setTimeout(function() {
          resolve(111);
        }, 1000);
      });
      promise
        .then(v => {
          console.log(v);
          return v;
        })
        .then(v => {
          console.log(v);
          return v;
        })
        .then(v => {
          alert(v);
        });
    </script>
  </body>
</html>
